// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDywqWVZKcfsCTHkJd6KrHXUHR26S6rczs',
    appId: '1:262772814476:web:43a5e9e720be4f742441a9',
    messagingSenderId: '262772814476',
    projectId: 'stockapp-a1717',
    authDomain: 'stockapp-a1717.firebaseapp.com',
    storageBucket: 'stockapp-a1717.appspot.com',
    measurementId: 'G-4WXDVSSLJW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcKx1Czgeti9vYmmM1F2EA1oTB58Q8590',
    appId: '1:262772814476:android:e20709bdc38a5f412441a9',
    messagingSenderId: '262772814476',
    projectId: 'stockapp-a1717',
    storageBucket: 'stockapp-a1717.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRpqGdr6MqlwU_0f9LKDBIrXO2WznhxSA',
    appId: '1:262772814476:ios:cdf31bb03cd542f22441a9',
    messagingSenderId: '262772814476',
    projectId: 'stockapp-a1717',
    storageBucket: 'stockapp-a1717.appspot.com',
    androidClientId: '262772814476-rat2g398gdj3s4o24aanipsv7cfqqj8k.apps.googleusercontent.com',
    iosClientId: '262772814476-f9d6ddekj9qfdsdklrpobso5lb15g3fg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRpqGdr6MqlwU_0f9LKDBIrXO2WznhxSA',
    appId: '1:262772814476:ios:cdf31bb03cd542f22441a9',
    messagingSenderId: '262772814476',
    projectId: 'stockapp-a1717',
    storageBucket: 'stockapp-a1717.appspot.com',
    androidClientId: '262772814476-rat2g398gdj3s4o24aanipsv7cfqqj8k.apps.googleusercontent.com',
    iosClientId: '262772814476-f9d6ddekj9qfdsdklrpobso5lb15g3fg.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
